# NumPy documentation

(https://numpy.org/doc/stable/user/quickstart.html)

***



In [1]:
import matplotlib as plt
import numpy as np

In [2]:
x = np.array([1,2,3])
print(x)

[1 2 3]


In [3]:
print(x.shape)

(3,)


In [4]:
x = np.array([[1,2],[3,4],[5,6]])
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
print(x.shape)

(3, 2)


In [6]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
print(x.shape)


(4, 3)


In [8]:
x = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(x)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
print(x.shape)

(2, 2, 3)


In [10]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [11]:
x1 = x +1
print(x1)

[[2 3]
 [4 5]]


In [12]:
x1 = np.array([[1,2], [3,4]])
x2 = np.array([[10,20],[30,40]])
x3 = x1 + x2
print(x3)

[[11 22]
 [33 44]]


In [13]:
print(x3.shape)

(2, 2)


In [14]:
x1 = np.array([[1,2,3], [4,5,6]])
x2 = np.array([[10],[20]])
x3 = x1 + x2
print(x3)

[[11 12 13]
 [24 25 26]]


In [15]:
a = np.arange(15).reshape(3,5)

In [16]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [17]:
a = np.arange(60).reshape(3,20)
print(a)


[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]]


In [18]:
c= np.array([[1,2],[3,4]],dtype=complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [19]:
b = np.arange(10,30,5)
print(b)

[10 15 20 25]


In [20]:
h= np.arange(0,2,0.3)
print(h)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [21]:
a=np.array([20,30,40,50])
b=np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [22]:
c=a-b

In [23]:
print(c)

[20 29 38 47]


In [24]:
a<35

array([ True,  True, False, False])